### ISSUE TITLE
violations choke on cppcheck result with empty location

### ISSUE THREAD

**Issue by amai2012** [tomasbjerre/violations-command-line#5]
The following command fails
````
C:\violations-command-line\build\libs>java -jar violations-command-line-1.21.5.jar -show-debug-info -v "CPPCHECK" "." ".*.xml$" "cppcheck"
Given parameters:
-show-debug-info, -v, CPPCHECK, ., .*.xml$, cppcheck

Parsed parameters:
Runner [violations=[[CPPCHECK, ., .*.xml$, cppcheck]], minSeverity=INFO, detailLevel=VERBOSE, maxViolations=2147483647, printViolations=true, diffFrom=, diffTo=, diffMinSeverity=INFO, gitRepo=., diffPrintViolations=false, diffMaxViolations=2147483647, diffDetailLevel=VERBOSE, maxReporterColumnWidth=0, maxRuleColumnWidth=10, maxSeverityColumnWidth=0, maxLineColumnWidth=0, maxMessageColumnWidth=50]
FINE .*.xml$ matches C:\violations-command-line\build\libs\.\cppcheck.xml
FINE .*.xml$ does not match C:\violations-command-line\build\libs\.\violations-command-line-1.21.5-javadoc.jar
FINE .*.xml$ does not match C:\violations-command-line\build\libs\.\violations-command-line-1.21.5-sources.jar
FINE .*.xml$ does not match C:\violations-command-line\build\libs\.\violations-command-line-1.21.5-tests.jar
FINE .*.xml$ does not match C:\violations-command-line\build\libs\.\violations-command-line-1.21.5.jar
INFO Found 1 reports in . with pattern .*.xml$
INFO     - C:\violations-command-line\build\libs\.\cppcheck.xml
SEVERE Error when parsing C:\violations-command-line\build\libs\.\cppcheck.xml as shadow.se.bjurr.violations.lib.parsers.CPPCheckParser content:

<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.8"/>
    <errors>
        <error id="cppcheckdata-pythonError" severity="error" msg="Failed to load pathlib. Upgrade python to 3.x or install pathlib with &apos;pip install pathlib&apos;." verbose="Failed to load pathlib. Upgrade python to 3.x or install pathlib with &apos;pip install pathlib&apos;." file0="P1.cpp.dump">
            <location file="" line="0" column="0"/>
        </error>
     </errors>
</results>

java.lang.NullPointerException: file
        at shadow.se.bjurr.violations.lib.util.Utils.checkNotNull(Utils.java:27)
        at shadow.se.bjurr.violations.lib.model.Violation.<init>(Violation.java:185)
        at shadow.se.bjurr.violations.lib.model.Violation$ViolationBuilder.build(Violation.java:35)
        at shadow.se.bjurr.violations.lib.parsers.CPPCheckParser.parseReportOutput(CPPCheckParser.java:107)
        at shadow.se.bjurr.violations.lib.reports.ViolationsFinder.findViolations(ViolationsFinder.java:35)
        at shadow.se.bjurr.violations.lib.ViolationsApi.violations(ViolationsApi.java:103)
        at se.bjurr.violations.main.Runner.getAllParsedViolations(Runner.java:471)
        at se.bjurr.violations.main.Runner.performTask(Runner.java:323)
        at se.bjurr.violations.main.Runner.main(Runner.java:312)
        at se.bjurr.violations.main.Main.main(Main.java:6)
````

on this input:
```` xml
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.8"/>
    <errors>
        <error id="cppcheckdata-pythonError" severity="error" msg="Failed to load pathlib. Upgrade python to 3.x or install pathlib with &apos;pip install pathlib&apos;." verbose="Failed to load pathlib. Upgrade python to 3.x or install pathlib with &apos;pip install pathlib&apos;." file0="P1.cpp.dump">
            <location file="" line="0" column="0"/>
        </error>
     </errors>
</results>
````

Maybe this issue should have been created in https://github.com/tomasbjerre/violations-lib/issues - but I didn't find a test application there...

Originally I was redirected from https://issues.jenkins.io/browse/JENKINS-68745 ...

**Comment by tomasbjerre** [comment]
Fixed here:
https://github.com/tomasbjerre/violations-lib/commit/5b3a01320de6eee1e2413465d021b5bdadb9a94b
